name: PySpark CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run PySpark tests
      #   run: |
      #     python -m pytest test.py

      - name: Run PySpark linting
        run: |
          ruff check  *.py mylib/*.py

      - name: Format PySpark code
        run: |
          black *.py mylib/*.py